// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicFooter: typeof import('./src/components/BasicFooter/index.vue')['default']
    BasicHeader: typeof import('./src/components/BasicHeader/index.vue')['default']
    BasicSider: typeof import('./src/components/BasicSider/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CommentItem: typeof import('./src/components/Comment/CommentItem.vue')['default']
    Control: typeof import('./src/components/BasicHeader/Control.vue')['default']
    DesciptionDetail: typeof import('./src/components/Common/DesciptionDetail.vue')['default']
    Description: typeof import('./src/components/Common/Description.vue')['default']
    DescriptionTitle: typeof import('./src/components/Common/DescriptionTitle.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ListItem: typeof import('./src/components/Common/ListItem.vue')['default']
    Loading: typeof import('./src/components/Common/Loading.vue')['default']
    LoadingPage: typeof import('./src/components/Common/LoadingPage.vue')['default']
    Loding: typeof import('./src/components/Common/Loding.vue')['default']
    PlaylistDetail: typeof import('./src/components/Common/PlaylistDetail.vue')['default']
    RecommendItem: typeof import('./src/components/RecommendItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Songlist: typeof import('./src/components/Common/Songlist.vue')['default']
    SongList: typeof import('./src/components/SongList/index.vue')['default']
  }
}

export {}
